WIP: Search for an existing client by name - Frontend
uwblueprint/project-read-frontend pull request #48
Opened 2021-06-25 02:03 UTC by jossmurphy

### Notion ticket link

https://www.notion.so/uwblueprintexecs/Search-for-an-existing-client-by-name-c9abac8344804d63ba8a9b3ca5f83ef4

[Search for an existing client by name](https://www.notion.so/uwblueprintexecs/9cb454262ed84c6299c0682c23f92ec5?v=1076bd30711a4a01838becee05f8b5a3)

### Implementation description
- added getFamilySearch to FamilyAPI.ts
- created several MUI react components (text field inputs, tables, buttons) to allow users to input First and/or last name, search, and get a table of families returned 

![image](https://user-images.githubusercontent.com/43387820/123356894-959d5b00-d536-11eb-9101-1ac31e6a24aa.png)
![image](https://user-images.githubusercontent.com/43387820/123356907-9cc46900-d536-11eb-8486-c5f3498aa0c3.png)
![image](https://user-images.githubusercontent.com/43387820/123356924-a2ba4a00-d536-11eb-8b4d-9807bc8cd7bd.png)

### Steps to test

1. run the backend and frontend 
2. localhost:3000/sessions   -> Add a client button
2. test First name search (e.g. John), last name search, first and last name, no names (should prompt user and not call to backend), incorrect search ( a user not in the database should return "No Results Found")
3. Add families via django admin to test the table scroll functionality when many results are returned 

### What should reviewers focus on?

@brittanylau 
Still needs to be implemented before merging
- user is met with a clean slate when opening dialog box again (reset the user input every time the box is opened)
- spacing could be nicer when we clean things up at the end 
- in a few places I use style={{}} which doesn't seem to be best practice ... is this ok or should I create a useStyles/className approach for all styling
- run linter

### Checklist

- [X] My PR name is descriptive and in imperative tense
- [ ] I have run the linter
- [X] I have requested a review from the PL, and/or other devs who have background knowledge on this PR or who will be building on top of this PR

2021-06-26 02:41 UTC, brittanylau commented
@jossmurphy nice work on this!! here's a quick summary of the additions I made:
* refactored out the search bar & results table to their own components (since we'll reuse this later for the "Add a guest" feature)
* used a `useEffect` hook to reset the form values when returning to the search form
* styling

feel free to take a look and let me know if I missed anything, or if you have any suggestions :)

2021-06-27 17:21 UTC, Tayef-Shah requested changes
Mapping the search fields may be cleaner in the long run. You'd just need to make a list of search fields in `DefaultFields.ts`. See below for details.

2021-06-27 17:21 UTC, Tayef-Shah commented on src/components/family-search/family-search-results-table/FamilySearchResultsTable.tsx
> +              <TableCell>{DefaultFields.NUM_CHILDREN.name}</TableCell>
Maybe we can replace this with something like
```suggestion
              {DefaultFamilySearchFields.map((searchField) => (
                <TableCell>{searchField.name}</TableCell>
              ))}
```

2021-06-27 17:21 UTC, Tayef-Shah commented on src/components/family-search/family-search-results-table/FamilySearchResultsTable.tsx
> +                  <TableCell>{family.num_children}</TableCell>
I'm thinking we can maybe make a change similar to this
```suggestion
                  {DefaultFamilySearchFields.map((searchField) => (
                    <TableCell>{(family as any)[searchField.id]}</TableCell>
                  ))}
```

2021-06-27 17:21 UTC, Tayef-Shah commented on src/components/family-search/family-search-results-table/FamilySearchResultsTable.tsx
> +import { DefaultFields } from "../../../constants/DefaultFields";
Maybe let's make a list in DefaultFields for the search
```suggestion
import { DefaultFamilySearchFields } from "../../../constants/DefaultFields";
```
inside `DefaultFields` you'll need to make a list like
```
export const DefaultFamilySearchFields: DefaultField[] = [
  DefaultFields.FIRST_NAME,
  DefaultFields.LAST_NAME,
  DefaultFields.PHONE_NUMBER,
  DefaultFields.EMAIL,
  DefaultFields.NUM_CHILDREN,
];
```

2021-06-27 21:12 UTC, brittanylau commented
@Tayef-Shah I personally don't think this level of abstraction is necessary for this component - we should avoid casting to `any` to promote type safety & readability. it should only really be used to pacify errors [while migrating a js project to ts](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any), which is why it's in the sidebar component atm

we should probably be changing that instead – made [this ticket](https://www.notion.so/uwblueprintexecs/Developer-Hub-30e9b6c82af24054b31acf7c5e822c89?p=b6d63545230e48e88535bf84fd2a4006) to track that :)

2021-06-27 21:45 UTC, Tayef-Shah commented
@brittanylau ah ok, sounds good then. I'll approve the changes.

2021-06-27 21:45 UTC, Tayef-Shah approved these changes

2021-06-27 22:40 UTC, brittanylau commented
@Tayef-Shah thank you!! 🙌

2021-06-28 01:36 UTC, merged